services:
  cli:
    image: riko2018/iot-cli
    container_name: cli
    restart: always
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
  api:
    image: riko2018/iot-api
    container_name: api
    restart: always
    ports:
      - '8000:8000'
      - '7000:7000'
    depends_on:
      broker:
        condition: service_started
      mongo:
        condition: service_started
    volumes:
      - ./api:/api
  broker:
    container_name: broker
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
  mongo:
    ports:
      - "27017:27017"
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db
volumes:
  mongo: