version: "3.8"

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command:
      [
        "certonly",
        "--standalone",
        "--non-interactive",
        "--agree-tos",
        "-m", "admin@gerara.ru",
        "-d", "gerara.ru",
        "-d", "www.gerara.ru"
      ]
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt

volumes:
  certbot-etc:
  wordpress: