services:
  cli:
    image: riko2018/iot-cli
    container_name: cli
    volumes:
      - cli:/cli
  api:
    image: riko2018/iot-api
    container_name: api
    restart: always
    ports:
      - "8000:8000"
      - "7000:7000"
    volumes:
      - certbot-etc:/etc/letsencrypt
    depends_on:
      broker:
        condition: service_started
      mongo:
        condition: service_started
  broker:
    container_name: broker
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
  mongo:
    ports:
      - "27017:27017"
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"

  wordpress:
    depends_on:
      - db
      - cli
    image: wordpress
    container_name: wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - cli:/var/www/html/wp-content/plugins/gerarareact/frontend
      - ./wp/apache-ssl.conf:/etc/apache2/sites-available/000-default.conf      
      - ./wp/gerarareact:/var/www/html/wp-content/plugins/gerarareact
    command:
      bash -c "a2enmod ssl && apache2-foreground"

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --force-renewal -d your_domain -d www.your_domain

volumes:
  mongo:
  api:
  certbot-etc:
  wordpress:
  dbdata:
  cli: