services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    #image: riko2018/iot-client
    env_file: ./.env.cli.deve
    container_name: cli
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    stdin_open: true
    tty: true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    #image: riko2018/iot-api
    env_file: ./.env.api.deve
    container_name: api
    restart: always
    ports:
      - '8000:8000'
      - '7000:7000'
    volumes:
      - ./api:/api
      - ./api/node_modules:/api/node_modules
    depends_on:
      broker:
        condition: service_started
  broker:
    build: ./broker
    container_name: broker
    #image: riko2018/iot-brocker
    ports:
      - 1883:1883
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
