services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: certonly --standalone --non-interactive --agree-tos \
      -m admin@gerara.ru \
      -d gerara.ru -d www.gerara.ru
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
      - wordpress:/var/www/html

volumes:
  certbot-etc:
  wordpress:
